module LazyJLLWrappers

export LazyArtifactPath, @generate_jll_from_toml
using Libdl

if VERSION >= v"1.6.0"
    using TOML, Artifacts, Preferences, Base.BinaryPlatforms
else
    using Pkg, Pkg.TOML, Pkg.Artifacts, Pkg.BinaryPlatforms
end

"""
    LazyArtifactPath

Helper type that stores an artifact hash and a subpath, then lazily resolves it
on-demand for e.g. `ccall()` and friends.  Caches its result so that lookup only
happens once.
"""
struct LazyArtifactPath
    artifact_hash::Base.SHA1
    subpath::String
    result::Ref{String}

    function LazyArtifactPath(artifact_hash, subpath)
        return new(artifact_hash, subpath, Ref{String}())
    end
end
function Base.string(lap::LazyArtifactPath)
    if !isassigned(lap.result)
        lap.result[] = joinpath(
            artifact_path(lap.artifact_hash),
            lap.subpath,
        )
    end
    return lap.result[]
end

"""
    JLLBlocks

A structured datatype that holds all the Expr blocks that we will generate for a JLL.
Call `synthesize()` to get the JLL's source code.
"""
struct JLLBlocks
    mod::Module
    top_level_blocks::Vector{Expr}
    init_blocks::Vector{Expr}

    function JLLBlocks(mod)
        return new(mod, Expr[], Expr[])
    end
end

# We need to glue expressions together a lot, but we also need them
# to all be top-level expressions.
function excat(ex_type::Symbol, exs::Union{Expr,Nothing}...)
    ex = Expr(ex_type)
    for exn in exs
        exn === nothing && continue
        if Meta.isexpr(exn, :block) || Meta.isexpr(exn, :toplevel)
            append!(ex.args, exn.args)
        else
            push!(ex.args, exn)
        end
    end
    return esc(ex)
end

function synthesize(jb::JLLBlocks)
    ret = excat(:block,
        jb.top_level_blocks...,
        quote
            function __init__()
                $(jb.init_blocks...)
            end
        end
    )
    Base.remove_linenums!(ret)
    # For debugging.  Note that this does not include the source listing for the `platform_augmentation_module`
    # because it needs to be evaluated during compilation and I have not yet figured out a good way to do that
    # and also have it appear here.
    #println(stderr, ret)
    return ret
end

include("Compat.jl")
include("GeneratorUtils.jl")
include("ExecutableProduct.jl")
include("FileProduct.jl")
include("StaticLibraryProduct.jl")
include("LibraryProduct.jl")
include("Runtime.jl")

"""
    flatten_products(jll, build)

`JLL.toml` keys a build's products by name, and states each library's identity once at
the top level rather than repeating it per build.  Emitters want one self-contained
record per product, so re-attach both here, in a stable order.
"""
function flatten_products(jll, build)
    identities = get(jll, "products", Dict{String,Any}())
    products = Dict{String,Any}[]
    for (name, product) in build["products"]
        product = merge(product, Dict{String,Any}("name" => name))
        identity = get(identities, name, nothing)
        if identity !== nothing && haskey(identity, "dlid")
            product["dlid"] = identity["dlid"]
        end
        push!(products, product)
    end
    return sort(products; by = p -> p["name"])
end

"""
    check_jll_format(jll, toml_path)

Refuse a `JLL.toml` written in a format this wrapper cannot read.  A record with no
`jll_format` marker predates the realization-group format, where a library product's
path moved into a `dynamic`/`static` sub-table, so reading it here would silently
misinterpret every library.
"""
function check_jll_format(jll, toml_path)
    if !haskey(jll, "jll_format")
        error("`$(toml_path)` declares no `jll_format`, so it predates v2.0 and describes " *
              "its library products in the older flat shape; it must be regenerated by a " *
              "current JLLGenerator.")
    end
    format = tryparse(VersionNumber, string(jll["jll_format"]))
    if format === nothing
        error("`$(toml_path)` declares an invalid `jll_format` of $(repr(jll["jll_format"]))")
    end
    if format.major != 2
        error("`$(toml_path)` declares `jll_format = \"$(jll["jll_format"])\"`, but this " *
              "version of LazyJLLWrappers reads v2 records.")
    end
    return format
end

macro generate_jll_from_toml()
    # Lookup TOML location from this module
    toml_path = joinpath(pkgdir(__module__), "JLL.toml")
    if !isfile(toml_path)
        throw(ArgumentError("Unable to load '$(toml_path)'!"))
    end

    # Read in the JLL metadata (allowing for preference overriding)
    if VERSION >= v"1.6.0"
        toml_path = load_preference(__module__, "toml_path", toml_path)
    end
    jll = TOML.parsefile(toml_path)
    check_jll_format(jll, toml_path)

    # The `JLLBlocks` object is where we store up each of the pieces of code
    # that will constitute this JLL, including top-level statements, `__init__()`
    # fragments, etc...  At the end of this macro, we call `synthesize()` on
    # this object to generate the end result.
    jb = JLLBlocks(__module__)

    # Select a single artifact to use; we make this choice at precompile time,
    # and assert that if the host platform is to change (e.g. the CUDA version
    # gets upgraded, the MPI engine changes) we require recompilation.  As of
    # this writing, that is enforced by erroring during `__init__()` where we
    # check that the "live" `HostPlatform()` matches the one that we were
    # compiled with.  In the future, we may have a mechanism to allow a
    # precompilation cache to invalidate itself, but we don't have it yet, so
    # just choose a triplet and store it for validation in `__init__()` later.
    # Note that while most JLLs only have a single artifact built for multiple
    # platforms, some JLLs can provide alternate artifact names (e.g. `default`
    # vs. `debug`), you can switch between which one you want to download
    # by setting the `artifact_name` preference:
    artifact_name = jll["name"]
    if VERSION >= v"1.6.0"
        artifact_name = load_preference(__module__, "artifact_name", artifact_name)
    end

    # If we have platform augmentation snippets, we need to evaluate them now,
    # and also insert the code into the end result JLL to be run again at
    # __init__() time, so that we can check that the platform augmentation
    # hasn't changed its mind since the last time we precompiled this JLL.
    platform = get_augmented_platform(jb, jll)
    build = select_artifact(jll["builds"], artifact_name, platform)

    # Right off the bat, if we don't have a matching platform, we just
    # instantly return the definition of a "dead" JLL:
    if build === nothing
        dead_jll_definition(jb)
        return synthesize(jb)
    end

    # Flatten the name-keyed product map back into the array the emitters expect,
    # folding each library's identity in from the top-level table where it is stated
    # once for the whole package.
    build = merge(build, Dict("products" => flatten_products(jll, build)))

    # Add top-level statements like exports, imports of other libraries,
    # declarations of globals, etc...
    top_level_statements(jb, build, platform)

    # Sort our library products so that they are in dependency-order.  Only the ones
    # with a shared realization take part: an archive is never loaded, so it has no
    # place in a load order.
    lib_products = [p for p in build["products"] if p["type"] == "library" && haskey(p, "dynamic")]
    function calc_depths(lib_products)
        # We ignore external dependencies
        ignored = Set{String}()
        for lib in lib_products
            for d in lib["dynamic"]["deps"]
                if occursin(".", d)
                    push!(ignored, d)
                end
            end
        end

        depths = Dict{String,Int}()
        while length(depths) != length(lib_products)
            for p in lib_products
                if !haskey(depths, p["name"])
                    tracked_deps = filter(d -> d ∉ ignored, p["dynamic"]["deps"])
                    if all(haskey(depths, d) for d in tracked_deps)
                        if isempty(tracked_deps)
                            depths[p["name"]] = 1
                        else
                            depths[p["name"]] = maximum(depths[d] for d in tracked_deps) + 1
                        end
                    end
                end
            end
        end
        return depths
    end
    lib_depths = calc_depths(lib_products)
    function product_isless(p1, p2)
        if lib_depths[p1["name"]] != lib_depths[p2["name"]]
            return isless(lib_depths[p1["name"]], lib_depths[p2["name"]])
        end
        return isless(p1["name"], p2["name"])
    end
    lib_products = sort(lib_products, lt=product_isless)

    # Do all the library products first, since we have to sort them specifically.
    for product in lib_products
        library_product_definition(jb, build, product)
    end

    # Also, create our `eager_mode()` function body which will open all of our
    # libraries and tell all of our dependencies to open their libraries too.
    # This allows these packages to co-exist with the old `JLLWrappers`
    build_eager_mode(jb, lib_products)
    
    # Next all the other products
    for product in build["products"]
        if product["type"] == "library"
            # Those with a shared realization were emitted above; the rest are
            # archives, which we can only offer as a path.
            if !haskey(product, "dynamic")
                static_library_product_definition(jb, build, product)
            end
        elseif product["type"] == "executable"
            executable_product_definition(jb, build, product)
        elseif product["type"] == "file"
            file_product_definition(jb, build, product)
        else
            throw(ArgumentError("Unknown product type '$(product["type"])'"))
        end
    end

    # If we have an `init_def`, insert that into our `init_blocks`
    init_def = get(build, "init_def", nothing)
    if init_def !== nothing
        push!(jb.init_blocks, Meta.parse(init_def))
    end

    init_footer(jb, build)
    return synthesize(jb)
end

end # module LazyJLLWrappers
